name: build node
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    paths:
      - node/**
jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        tag: 
          - 5
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Install buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.5.1
          buildkitd-flags: --debug
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./node
          file: ./node/${{ matrix.tag }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/bartixxx32/images:node_${{ matrix.tag }}
