name: build oses
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    paths:
      - oses/**
jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        oses: 
          - debian
          - debian_mono-5
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Install buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.5.1
          buildkitd-flags: --debug
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./oses/${{ matrix.oses }}
          file: ./oses/${{ matrix.oses }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/mikolajkolek/images:${{ matrix.oses }}